"""Reproducibility guard: the committed derived data must match a fresh rebuild.

This kills a whole class of bug — committing an index generated by an older
version of the code. If someone clones the repo and runs the pipeline, they
must get the numbers shown in the dashboard.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

PRICES = ROOT / "data" / "prix_actuels.csv"
INDEX = ROOT / "data" / "indice_quotidien.csv"


@pytest.mark.skipif(not (PRICES.exists() and INDEX.exists()),
                    reason="data files not present")
def test_daily_index_reproduces_committed_file():
    from build_daily_index import compute_daily

    rebuilt, _ = compute_daily(pd.read_csv(PRICES))
    committed = pd.read_csv(INDEX)

    m = committed.merge(rebuilt, on="date", suffixes=("_committed", "_rebuilt"))
    assert len(m) == len(committed), "date mismatch between committed and rebuilt"
    # the committed index value must equal a fresh recomputation
    assert (m["indice_quotidien_committed"] - m["indice_quotidien_rebuilt"]).abs().max() < 0.01


def test_reference_series_strips_promotions():
    """A -20% promotion must move the displayed index but NOT the reference one."""
    from build_daily_index import compute_daily

    df = pd.DataFrame([
        {"date": "2026-01-01", "product_id": "x", "produit": "X", "categorie": "epicerie",
         "prix": 100.0, "prix_reference": 100.0, "en_promo": False},
        {"date": "2026-01-02", "product_id": "x", "produit": "X", "categorie": "epicerie",
         "prix": 80.0, "prix_reference": 100.0, "en_promo": True},
    ])
    out, _ = compute_daily(df)
    last = out.iloc[-1]
    assert last["indice_quotidien"] == pytest.approx(80.0)   # displayed follows the promo
    assert last["indice_reference"] == pytest.approx(100.0)  # reference ignores it
    assert last["pct_en_promo"] == pytest.approx(100.0)
